run:
  tests: true
  timeout: 5m
  concurrency: 4
  modules-download-mode: readonly

linters:
  enable-all: true
  disable:
    # unwanted linters
    - depguard # would have loved to add but doesn't seem to work correctly
    - err113
    - exhaustruct
    - gochecknoglobals
    - gochecknoinits
    - gomnd
    - gomoddirectives
    - mnd

linters-settings:
  dogsled:
    max-blank-identifiers: 1
  misspell:
    locale: US
  nolintlint:
    allow-unused: false
    require-explanation: true
    require-specific: true
  varnamelen:
    ignore-names:
      - tc
