version: "2"
linters:
  default: all
  disable:
    - depguard
    - err113
    - exhaustruct # requires every field to be instantiated in e.g. struct creation
    - gochecknoglobals
    - gomoddirectives
    - mnd
    - varnamelen
formatters:
  enable:
    - gofumpt
run:
  go: "1.23"
